/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: ({ colors }) => ({
        sideBarBlue: "#0096ff",
        headerBlue: "#00B8FF",
        dayoMint: "#40D5D3",
        dayoRed: "#FCCFD2",
        dayoOrange: "#FB6D21",
        dayoLightBlue: "#D6EEFB",
        dayoAshBlue: "#1EA5EE",
        dayoDarkGray: "#2A2F3A",
        dayoNeutral: "#EFF0F4",
        sideBarBG: "#055A70",
        chartBlue: "#09ADD6",
        beforeHover: "#078EB0",
        afterHover: "#0AC2F0",
        lightBlue: "#0ACCFC",
        accessOrange: "#e58b34",
        accessBlue: "#025dff",
        gtbOrange: "#F5594C",
        inherit: colors.inherit,
        current: colors.current,
        transparent: colors.transparent,
        black: colors.black,
        white: colors.white,
        slate: colors.slate,
        gray: colors.gray,
        zinc: colors.zinc,
        neutral: colors.neutral,
        stone: colors.stone,
        red: colors.red,
        orange: colors.orange,
        amber: colors.amber,
        yellow: colors.yellow,
        lime: colors.lime,
        green: colors.green,
        emerald: colors.emerald,
        teal: colors.teal,
        cyan: colors.cyan,
        sky: colors.sky,
        blue: colors.blue,
        indigo: colors.indigo,
        violet: colors.violet,
        purple: colors.purple,
        fuchsia: colors.fuchsia,
        pink: colors.pink,
        rose: colors.rose,
      }),
    },
  },
  plugins: [],
};
